seneca_body_1 = File.read(File.join(Rails.root, 'db', 'texts', 'seneca_body_1.txt'))
seneca_body_2 = File.read(File.join(Rails.root, 'db', 'texts', 'seneca_body_2.txt'))
plutarch_body_1 = File.read(File.join(Rails.root, 'db', 'texts', 'plutarch_body_1.txt'))
plutarch_body_2 = File.read(File.join(Rails.root, 'db', 'texts', 'plutarch_body_2.txt'))
erasmus_body_1 = File.read(File.join(Rails.root, 'db', 'texts', 'erasmus_body_1.txt'))
montaigne_body_1 = File.read(File.join(Rails.root, 'db', 'texts', 'montaigne_body_1.txt'))
montaigne_body_2 = File.read(File.join(Rails.root, 'db', 'texts', 'montaigne_body_2.txt'))
twain_body_1 = File.read(File.join(Rails.root, 'db', 'texts', 'twain_body_1.txt'))
twain_body_2 = File.read(File.join(Rails.root, 'db', 'texts', 'twain_body_2.txt'))
thoreau_body_1 = File.read(File.join(Rails.root, 'db', 'texts', 'thoreau_body_1.txt'))
thoreau_body_2 = File.read(File.join(Rails.root, 'db', 'texts', 'thoreau_body_2.txt'))
emerson_body_1 = 
emerson_body_2 = 
shaw_body_1 = 
shaw_body_2 = 
muir_body_1 = 
muir_body_2 = 
zs_body_1 = 
zs_body_2 = 
wilde_body_1 = 
wilde_body_2 = 
dubois_body_1 = 
dubois_body_2 = 
goldman_body_1 = 
goldman_body_2 = 
beerbohm_body_1 = 
beerbohm_body_2 = 
woolf_body_1 = 
woolf_body_2 = 
gandhi_body_1 = 
gandhi_body_2 = 
fanon_body_1 = 
fanon_body_2 = 